#!/bin/bash

# Set up proxies
export http_proxy=http://proxy-prod-dku.oit.duke.edu:3128
export https_proxy=http://proxy-prod-dku.oit.duke.edu:3128

echo "Proxies set up successfully"

# Check if .git directory exists and remove it if it does
if [ -d ".git" ]; then
  echo "Removing existing .git directory"
  rm -rf .git
fi

# Initialize a new Git repository
echo "Initializing a new Git repository"
git init

# Create a .gitignore file to exclude all data files except title.high_quality.tsv
echo "Updating .gitignore file"
cat > .gitignore << 'EOL'
# Logs
logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
pnpm-debug.log*
lerna-debug.log*
.pnpm-debug.log*

# Diagnostic reports (https://nodejs.org/api/report.html)
report.[0-9]*.[0-9]*.[0-9]*.[0-9]*.json

# Runtime data
pids
*.pid
*.seed
*.pid.lock

# Directory for instrumented libs generated by jscoverage/JSCover
lib-cov

# Coverage directory used by tools like istanbul
coverage
*.lcov

# nyc test coverage
.nyc_output

# Node.js
node_modules
node_modules/
dist
dist-ssr
*.local
jspm_packages/

# Snowpack dependency directory (https://snowpack.dev/)
web_modules/

# TypeScript cache
*.tsbuildinfo

# Editor directories and files
.vscode/*
!.vscode/extensions.json
.idea
.DS_Store
*.suo
*.ntvs*
*.njsproj
*.sln
*.sw?

# SSL certificates
ssl/

# Environment variables
.env
.env.local
.env.development.local
.env.test.local
.env.production.local

# Large data files (exceed GitHub limits)
src/data/*
!src/data/title.high_quality.tsv
public/title.crew.tsv
public/title.ratings.tsv

# Firebase
.firebase/
firebase-debug.log
firebaserc

# Server logs
server.log
server.pid
filterbubble.log

# Grunt intermediate storage (https://gruntjs.com/creating-plugins#storing-task-files)
.grunt

# Bower dependency directory (https://bower.io/)
bower_components

# node-waf configuration
.lock-wscript

# Compiled binary addons (https://nodejs.org/api/addons.html)
build/Release

# Optional npm cache directory
.npm

# Optional eslint cache
.eslintcache

# Optional stylelint cache
.stylelintcache

# Microbundle cache
.rpt2_cache/
.rts2_cache_cjs/
.rts2_cache_es/
.rts2_cache_umd/

# Optional REPL history
.node_repl_history

# Output of 'npm pack'
*.tgz

# Yarn Integrity file
.yarn-integrity

# parcel-bundler cache (https://parceljs.org/)
.cache
.parcel-cache

# Next.js build output
.next
out

# Nuxt.js build / generate output
.nuxt

# Gatsby files
.cache/
# Comment in the public line in if your project uses Gatsby and not Next.js
# https://nextjs.org/blog/next-9-1#public-directory-support
# public

# vuepress build output
.vuepress/dist

# vuepress v2.x temp and cache directory
.temp

# vitepress build output
**/.vitepress/dist

# vitepress cache directory
**/.vitepress/cache

# Docusaurus cache and generated files
.docusaurus

# Serverless directories
.serverless/

# FuseBox cache
.fusebox/

# DynamoDB Local files
.dynamodb/

# TernJS port file
.tern-port

# Stores VSCode versions used for testing VSCode extensions
.vscode-test

# yarn v2
.yarn/cache
.yarn/unplugged
.yarn/build-state.yml
.yarn/install-state.gz
.pnp.*
.vercel
EOL

# Add all files
echo "Adding files to Git"
git add .

# Commit the changes
echo "Committing changes"
git commit -m "Initial commit"

# Ask for GitHub repository URL
echo "Please enter your GitHub repository URL (e.g., https://github.com/username/repo.git):"
read github_repo

# Add the GitHub repository as a remote
echo "Adding GitHub repository as remote"
git remote add origin $github_repo

# Push to GitHub
echo "Pushing to GitHub"
git push -u origin master

echo "Done! Your project has been pushed to GitHub."
