<template>
  <div class="entry-container">
    <div class="card entry-card">
      <h2 class="card-title">Thank you for participating in our research study on movie recommendations generated by LLM.</h2>
      <p class="entry-description">
        This study is designed to evaluate your experience with LLM-generated movie recommendations, focusing on both the quality of the recommendations and the diversity of the content.<br><br>
We have developed a conversational movie recommendation system that features AI agents making recommendations based on user preferences. You will be randomly assigned to one of our recommendation interfaces to test its effectiveness. We aim to understand how different AI recommendation approaches affect user perceptions of recommendation quality and diversity.

      </p>
      
      <!-- <div class="study-overview">
        <h3>Study Overview:</h3>
        <ol>
          <li>Complete an initial questionnaire about your background and preferences</li>
          <li>Engage in a first conversation with an AI assistant</li>
          <li>Engage in a second conversation with AI assistants</li>
          <li>Complete a mid-study questionnaire about your experience</li>
          <li>Complete a final questionnaire about your overall experience</li>
        </ol>
      </div> -->
      
      <div class="procedures-section">
        <h2 class="card-title">Study Procedure</h2>
        <p>
          The study will proceed through the following steps:<br><br>
        </p>
        <ol>
          <li><strong>Initial Questionnaire:</strong> <br><br>You will begin by filling out a brief questionnaire regarding your demographic information (e.g., age, gender) and your general movie preferences.<br><br></li>
          <li><strong>Movie Recommendation Introduction:</strong> <br><br>You'll be introduced to the movie recommendation system and learn about how the conversational AI works. The system will then randomly assign you to one of three different recommendation interfaces for testing.<br><br></li>
          <li><strong>Interact with the <span class="blue-text">Recommendation System</span></strong> <br><br>You'll interact with your assigned conversational system. During this session, you will engage in <span class="red-text">a minimum of three rounds</span> of interaction with the AI to explore movie recommendations that interest you.<br><br></li>
          <li><strong>Post-interaction Questionnaire</strong> <br><br>After using the system, you will complete a short questionnaire about your experience and satisfaction with the recommendations made by the system.<br><br></li>
          <li><strong>Open-ended Questions</strong> <br><br>At the conclusion of both sessions, you'll be asked to complete a set of open-ended questions that covers your overall experience, preferences among the systems, and your thoughts on the AI-generated recomendations.<br><br></li>
          <li><strong>Study Completion</strong> <br><br>Once the questionnaire is submitted, your participation will be complete, and you'll receive your reward.<br><br></li>
        </ol>
        <p>
          Throughout the study, we will collect data on your interactions to understand how different AI systems influence user decisions and satisfaction. Your participation is greatly appreciated and will contribute to advancing research on human-AI collaboration in recommendation systems.
        </p>
        <!-- <p>
          <strong>Important:</strong> In both the first-round and second-round conversation pages, you are required to send at least 5 messages to the AI chatbot. This requirement ensures you have sufficient interaction time with the system and can fully experience the conversation. You must interact at least 5 times in each round before proceeding to the next stage of the study.
        </p> -->
      </div>
      
      <div class="duration-section">
        <h2 class="card-title">DURATION:</h2>
        <p>
          This study will take about 20 minutes to complete (including time for filling out required and optional questionnaires).
        </p>
      </div>
      
      <div class="benefits-section">
        <h2 class="card-title">BENEFITS:</h2>
        <p>
          This user study is to evaluate a movie recommendation chatbot that aims to recommend movies to you through conversation. 
          As evaluators of this chatbot, we believe it will be beneficial for you to experience a conversational chatbot for movie recommendations, 
          learn the new dialog-based interaction model and help us improve the chatbot design.
        </p>
      </div>
      
      <div class="consent-section">
        <h3>Consent to Participate:</h3>
        <p>
          By participating in this study, you agree that we may collect data about your interactions,
          including your conversations with the AI and your questionnaire responses. All data will be
          anonymized and used solely for research purposes.
        </p>
        
        <div class="form-group">
          <label class="checkbox-container">
            <input type="checkbox" v-model="consentGiven">
            I understand and agree to participate in this research study
          </label>
        </div>
      </div>
      
      <button 
        class="btn start-btn" 
        :disabled="!consentGiven" 
        @click="startStudy">
        Begin Study
      </button>
    </div>
  </div>
</template>

<script>
import { getUserId } from '../utils/userIdentifier';
import { logSystemEvent, logUserEvent } from '../services/loggingService';

export default {
  name: 'AppEntry',
  data() {
    return {
      consentGiven: false
    };
  },
  created() {
    // 1. 从当前 URL 的查询字符串中获取 'condition' 参数
    const condition = this.$route.query.condition;

    // 2. 检查参数是否存在
    if (condition) {
      // 3. 如果存在，就将它保存到 sessionStorage 中
      sessionStorage.setItem('experimentCondition', condition);
      console.log(`Experiment condition '${condition}' has been set.`);
    }

    // Generate or retrieve user ID as soon as they land on the entry page
    const userId = getUserId();
    
    // Log entry to the application
    logSystemEvent('study_entry', {
      userId,
      timestamp: new Date().toISOString()
    });
  },
  methods: {
    startStudy() {
      if (!this.consentGiven) {
        return;
      }
      
      // Log consent and study start
      logUserEvent('consent_given', {
        timestamp: new Date().toISOString()
      });
      
      // Navigate to the initial questionnaire
      this.$router.push({ name: 'InitialQuestionnaire' });
    }
  }
};
</script>

<style scoped>
.entry-container {
  display: flex;
  justify-content: center;
  align-items: center;
  min-height: 100vh;
  width: 100%;
  padding: 0;
}

.entry-card {
  max-width: 100%;
  width: 95%;
  max-height: 90vh;
  overflow-y: auto;
  margin: 0;
  border-radius: 0;
  box-shadow: none;
  padding: 4.5rem;
}

.entry-description {
  margin-bottom: 2rem;
  font-size: 1.1rem;
  line-height: 1.6;
}

.research-background,
.study-overview,
.procedures-section,
.duration-section,
.benefits-section {
  margin-bottom: 2rem;
}

.research-background h3,
.study-overview h3,
.procedures-section h3,
.duration-section h3,
.benefits-section h3 {
  margin-bottom: 1rem;
  color: var(--primary-color);
}

.research-background p,
.procedures-section p,
.duration-section p,
.benefits-section p {
  font-size: 1.1rem;
  line-height: 1.6;
  text-align: justify;
}

.study-overview ol,
.procedures-section ol {
  padding-left: 1.5rem;
}

.study-overview li,
.procedures-section li {
  margin-bottom: 0.5rem;
}

.consent-section {
  margin-bottom: 2rem;
  padding: 1.5rem;
  background-color: var(--light-gray);
  border-radius: var(--border-radius);
}

.consent-section h3 {
  margin-bottom: 1rem;
  color: var(--primary-color);
}

.checkbox-container {
  display: flex;
  align-items: center;
  cursor: pointer;
  font-weight: 600;
}

.checkbox-container input {
  margin-right: 0.5rem;
  transform: scale(1.2);
}

.start-btn {
  width: 100%;
  padding: 0.75rem;
  font-size: 1.1rem;
  margin-top: 1rem;
}

.start-btn:disabled {
  background-color: var(--secondary-color);
  cursor: not-allowed;
  opacity: 0.7;
}
.blue-text {
  color:var(--primary-color) ;
}
.red-text {
  color: red;
  font-weight: bold;
}
</style>
